### ISSUE TITLE
 failed: Put "https://127.0.0.1:8200/v1/auth/kubernetes/login": dial tcp 127.0.0.1:8200: connect: connection refused

### ISSUE THREAD

**Issue by 13567436138** [crumbhole/argocd-vault-replacer#135]
# 

```
kubectl exec -ti vault-0 -n vault /bin/sh 

vault policy write app app-policy.hcl

[root@mycompany secret]# cat app-policy.hcl 
path "kv/*" {
  capabilities = ["read"]
}

vault auth enable kubernetes

vault write auth/kubernetes/config \
   token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
   kubernetes_host=https://${KUBERNETES_PORT_443_TCP_ADDR}:443 \
   kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt


vault write auth/kubernetes/role/myapp \
   bound_service_account_names=argocd-repo-server \
   bound_service_account_namespaces=argocd \
   policies=app \
   ttl=1024h
   
   
   
   
vault kv put kv/cred username=mark password=123

```

secret/argocd-vault-replacer/argocd-vault-replacer-credentials.yaml

```
apiVersion: v1
stringData:
  VAULT_ADDR: http://vault-active.vault.svc:8200
  AVP_AUTH_TYPE: k8s
  AVP_MOUNT_PATH: auth/kubernetes
  AVP_K8S_ROLE: myapp
  AVP_TYPE: vault
kind: Secret
metadata:
  name: argocd-vault-replacer-credentials
  namespace: argocd
type: Opaque
```

secret/argocd-vault-replacer/cmp-plugin-replacer.yaml

kubectl apply -f cmp-plugin-replacer.yaml -n argocd

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin-replacer
data:
  avr-kustomize.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-replacer-kustomize
    spec:
      allowConcurrency: true
      generate:
        command: ["sh", "-c"]
        args: ["kustomize build . | argocd-vault-replacer"]
      discover:
        fileName: "./argocd-vault-replacer-kustomize"
      lockRepo: false
  avr-helm.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-replacer-helm
    spec:
      allowConcurrency: true
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build"]
      generate:
        command: [sh, -c]
        args: ["helm template -n $ARGOCD_APP_NAMESPACE $ARGOCD_APP_NAME . | argocd-vault-replacer"]
      discover:
        fileName: "./argocd-vault-replacer-helm"
      lockRepo: false
  avr.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-replacer
    spec:
      allowConcurrency: true
      generate:
        command: ["argocd-vault-replacer"]
      discover:
        fileName: "./argocd-vault-replacer"
      lockRepo: false
---
```

secret/argocd-vault-replacer/patch.yaml

kubectl patch -n argocd  deploy argocd-repo-server --patch "$(cat patch.yaml)"

```
spec:
  template:
    spec:
      automountServiceAccountToken: true
      volumes:
        - configMap:
            name: cmp-plugin-replacer
          name: cmp-plugin-replacer
        - name: custom-tools
          emptyDir: {}
      initContainers:
      - name: argocd-vault-replacer-install
        image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/argocd-vault-replacer:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - name: custom-tools
          mountPath: /usr/local/bin/argocd-vault-replacer
          subPath: argocd-vault-replacer
        envFrom:
          - secretRef:
              name: argocd-vault-replacer-credentials
      - name: avr-helm
        command: [/var/run/argocd/argocd-cmp-server]
        image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/argocd:v2.6.7
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: avr-helm.yaml
            name: cmp-plugin-replacer
          - name: custom-tools
            subPath: argocd-vault-replacer
            mountPath: /usr/local/bin/argocd-vault-replacer
      - name: avr-kustomize
        command: [/var/run/argocd/argocd-cmp-server]
        image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/argocd:v2.6.7
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: avr-kustomize.yaml
            name: cmp-plugin-replacer
          - name: custom-tools
            subPath: argocd-vault-replacer
            mountPath: /usr/local/bin/argocd-vault-replacer
      - name: avr
        command: [/var/run/argocd/argocd-cmp-server]
        image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/argocd:v2.6.7
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: avr.yaml
            name: cmp-plugin-replacer
          - name: custom-tools
            subPath: argocd-vault-replacer
            mountPath: /usr/local/bin/argocd-vault-replacer
```

secret/argocd-vault-plugin/ap-clusterResourceWhitelist.yaml

kubectl apply -f ap-clusterResourceWhitelist.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  sourceRepos:
    - https://gitee.com/hxpgit/argocd.git
  destinations:
    - server: https://192.168.229.153:6443
      namespace: demo
      name: cluster1
    - server: https://192.168.229.156:6443
      namespace: demo
```

secret/app-argocd-vault-replacer.yaml

kubectl apply -f app-argocd-vault-replacer.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  destination:
    namespace: demo
    name: cluster1
  source:
    repoURL: https://gitee.com/hxpgit/argocd.git
    path: demo1/secretManager/argocd-vault-replacer
    targetRevision: HEAD 
    plugin: {}
  project: project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

```
Message:            ComparisonError: rpc error: code = Unknown desc = plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: `argocd-vault-replacer` failed exit status 1: 2023/05/10 09:35:51 Processing <secret:kv/data/cred~username> failed: Put "https://127.0.0.1:8200/v1/auth/kubernetes/login": dial tcp 127.0.0.1:8200: connect: connection refused
Processing <secret:kv/data/cred~password> failed: Put "https://127.0.0.1:8200/v1/auth/kubernetes/login": dial tcp 127.0.0.1:8200: connect: connection refused

GROUP  KIND    NAMESPACE  NAME                STATUS   HEALTH  HOOK  MESSAGE
       Secret  demo       example-annotation  Unknown                
FATA[0027] Operation has completed with phase: Error
```

the env is injected
argocd@argocd-repo-server-7c87c9f7d-hghp7:~$ echo $AVP_TYPE
vault
argocd@argocd-repo-server-7c87c9f7d-hghp7:~$ echo $VAULT_ADDR
http://vault-active.vault.svc:8200

why 127.0.0.1

**Comment by 13567436138** [comment]
secret changed to
```
apiVersion: v1
stringData:
  VAULT_ADDR: http://vault-active.vault.svc:8200
  VAULT_TOKEN: hvs.t2znvn7BgCYfshkgt7UXJ4JS
  VAULT_ROLE: myapp
  VAULT_AUTH_PATH: auth/kubernetes
kind: Secret
metadata:
  name: argocd-vault-replacer-credentials
  namespace: argocd
type: Opaque
```
